name: Build Kernel
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        run: |
          git clone --depth=1 -b lineage-23.2 https://github.com/LineageOS/android_kernel_oneplus_sm8150.git kernel
      - name: Fix compiler_types.h
        run: |
          cd kernel
          sed -i 's/#if __has_attribute(__fallthrough__)/#if 1/' include/linux/compiler_types.h
      - name: Build kernel
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu -y
          make vendor/sm8150-perf_defconfig
          make -j$(nproc) Image.gz-dtb
      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel/arch/arm64/boot/Image.gz-dtb
